### ISSUE TITLE
[Dep]: Update intl dependency 

### ISSUE THREAD

**Issue by lisovyk** [flutter-form-builder-ecosystem/form_builder_validators#137]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package/Plugin version

11.0.0

### Platforms

- [X] Android
- [X] iOS
- [ ] Linux
- [ ] MacOS
- [ ] Web
- [ ] Windows

### Flutter doctor

<details>
  <summary>Flutter doctor</summary>

```bash
% flutter doctor -v
[✓] Flutter (Channel stable, 3.24.3, on macOS 15.1.1 24B91 darwin-arm64, locale en-UA)
    • Flutter version 3.24.3 on channel stable at /Users/vladli/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2663184aa7 (3 months ago), 2024-09-11 16:27:48 -0500
    • Engine revision 36335019a8
    • Dart version 3.5.3
    • DevTools version 2.37.3

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/vladli/Library/Android/sdk
    • Platform android-34, build-tools 33.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16B40
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.95.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.102.0

[✓] Connected device (4 available)
    • iPhone SE (2nd generation) (mobile) • 35C4AFCC-A8B1-49D4-B883-17E641AD1FD3 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-2 (simulator)
    • macOS (desktop)                     • macos                                • darwin-arm64   • macOS 15.1.1 24B91 darwin-arm64
    • Mac Designed for iPad (desktop)     • mac-designed-for-ipad                • darwin         • macOS 15.1.1 24B91 darwin-arm64
    • Chrome (web)                        • chrome                               • web-javascript • Google Chrome 131.0.6778.109

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

### Minimal code example

<details>
  <summary>Code sample</summary>

```dart

```

</details>

### Current Behavior

Resolving dependencies...
Resolving dependencies...
Because my_app depends on form_builder_validators ^11.0.0 which depends on intl ^0.19.0, intl ^0.19.0 is required.
So, because my_app depends on intl ^0.20.1, version solving failed.

### Expected Behavior

form_builder_validators depends on latest intl

### Steps To Reproduce

...

**Comment by deandreamatias** [comment]
Hi!
Can't update intl dependency (now) because need to be the same version used on flutter_localizations
https://github.com/flutter/flutter/blob/17025dd88227cd9532c33fa78f5250d548d87e9a/packages/flutter_localizations/pubspec.yaml#L14

**Comment by prijindal** [comment]
flutter_localizations has been updated to 0.20.2. Can this be reconsidered?

**Comment by deandreamatias** [comment]
> flutter_localizations has been updated to 0.20.2. Can this be reconsidered?

@prijindal on stable version of Flutter (3.29), still using 0.19, so can't update
https://github.com/flutter/flutter/blob/35c388afb57ef061d06a39b537336c87e0e3d1b1/packages/flutter_localizations/pubspec.yaml#L14

**Comment by deepak-kumar-swain** [comment]
> > flutter_localizations has been updated to 0.20.2. Can this be reconsidered?
> 
> [@prijindal](https://github.com/prijindal) on stable version of Flutter (3.29), still using 0.19, so can't update https://github.com/flutter/flutter/blob/35c388afb57ef061d06a39b537336c87e0e3d1b1/packages/flutter_localizations/pubspec.yaml#L14

The current Stable version is 3.32.3

Please do update the version supported. Got Stuck in development.
