### ISSUE TITLE
Error with validate() and blank field

### ISSUE THREAD

**Issue by h-unterp** [flutter-form-builder-ecosystem/form_builder_validators#16]
Seems to happen with a blank field? As it works fine when there is text in the field.

`No instance of FormBuilderLocalizations was loaded. Try to initialize the FormBuilderLocalizations delegate before accessing FormBuilderLocalizations.current.`

```dart
                   onPressed: () {
                        if (!_form.currentState!.validate()) {
                          return;
                        }
```

**Comment by deandreamatias** [comment]
Do you [setup the localizations](https://github.com/flutter-form-builder-ecosystem/form_builder_validators#setup)?

**Comment by deandreamatias** [comment]
If this still a issue, with [this PR](https://github.com/flutter-form-builder-ecosystem/form_builder_validators/pull/22) may be solved
