### ISSUE TITLE
Change default error arabic Text message

### ISSUE THREAD

**Issue by MoElkilany** [flutter-form-builder-ecosystem/form_builder_validators#20]
I want to change this text to my custom text in all form builder validators in the app.

<img width="301" alt="Screen Shot 2022-10-20 at 10 40 00 AM" src="https://user-images.githubusercontent.com/45436838/196902016-4207ca5f-0a8a-4d33-a238-7a9e6a041559.png">

**Comment by deandreamatias** [comment]
You need set your own string on `errorText` paramater on each validator that you want
