### ISSUE TITLE
Is Traditional Chinese continue supported ?

### ISSUE THREAD

**Issue by dessonchan** [flutter-form-builder-ecosystem/form_builder_validators#34]
## Environment

**Package name:** form_builder_validators

## Describe your question

It was documented on README, but I can't see `messages_zh_hant.dart` on `lib/localization/intl`

`messages_zh_hant.dart` was deleted on commit `46562bd792f59ef1a3a12538dd5d49063055fab6`

**Comment by dessonchan** [comment]
To someone who facing the same problem, downgrade `form_builder_validators` to `^8.3.0` will fix.

**Comment by deandreamatias** [comment]
I think that is replace by zh, I don't know why.
If you can @dessonchan, please create a PR to restore this translate file
Thanks!
