### ISSUE TITLE
intl dependency

### ISSUE THREAD

**Issue by vasil-boshnyakov** [flutter-form-builder-ecosystem/form_builder_validators#35]
## Environment

form_builder_validators: ^8.4.0 (latest)

<details>
  <summary>Flutter doctor</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.10, on macOS 13.1 22C65 darwin-arm, locale en-BG)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.74.3)
[✓] VS Code (version 1.74.3)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!
```

</details>

<details>
  <summary>Code sample</summary>

```dart
Because form_builder_validators 8.4.0 depends on intl ^0.17.0 and no versions of form_builder_validators match >8.4.0 <9.0.0, form_builder_validators ^8.4.0 requires intl ^0.17.0.
```

</details>

## Description

`intl` package has version 0.18.0 and `form_builder_validators` depends on 0.17.0

## Steps to reproduce

add the to `pubspec.yaml` as dependency:
```
intl: ^0.18.0
```

**Comment by deandreamatias** [comment]
In this moment, I can't upgrade the intl version because:

> Because form_builder_validators depends on flutter_localizations from sdk which depends on intl 0.17.0, intl 0.17.0 is required.

**Comment by huongtran84** [comment]
flutter_localizations updated  package intl to 0.18.0

**Comment by deandreamatias** [comment]
> flutter_localizations updated package intl to 0.18.0

Isn't true. The currently version of intl on Flutter stable (3.7.5), is 0.17.0. Take on [this issue](https://github.com/flutter/flutter/issues/117163#issuecomment-1442453322) and this image from Flutter repository (look the tag selected)
![image](https://user-images.githubusercontent.com/21011641/221037903-3c5e24f6-c46f-490d-b1de-87de4642230e.png)

**Comment by deandreamatias** [comment]
The only way if you want use last intl version, is override this dependency

**Comment by sarbogast** [comment]
Now that Flutter 3.10 depends explicitly on intl 0.18.0, it's basically impossible to build a project with flutter_form_builder dependencies with Flutter 3.10. 
No shame on you guys, they have the same issue with firebase_auth_web that they maintain themselves.
But still, I think it's time to solve this issue without forcing an override

**Comment by deandreamatias** [comment]
@sarbogast I work on this but differently that firebase contributors, I make for free hehhehe
You can use the last version on this package on [pre-release](https://pub.dev/packages/form_builder_validators/versions/9.0.0-dev.2). I will release a new pre-release of flutter_form_builder too
