### ISSUE TITLE
Support for async will be added in the future

### ISSUE THREAD

**Issue by TianYuWord** [flutter-form-builder-ecosystem/form_builder_validators#39]
## Environment

any device

**Package name and version:**  

\form_builder_validators-8.4.0\lib\src\form_builder_validators.dart
form_builder_validators: ^8.4.0

## Description

**What you'd like to happen:**
Add support for async because I want to make a network request in a custom method

**Alternatives you've considered:**   
Modify the source code, but it's too much work, and I don't know many details in the code

**Images:**   
![error](https://user-images.githubusercontent.com/54766334/215521491-5475ffb0-0076-45b2-9e99-9debddf38d01.png)

**Comment by ScottWallace** [comment]
This was marked as "completed", but I don't find this feature to be there. Seems like an important one. I want to validate the existence of an email address against a server, which would require async/await. Can this be re-opened?

**Comment by rlee1990** [comment]
Will there be any support for this?

**Comment by deandreamatias** [comment]
This doesn't exactly apply here, but here https://github.com/flutter-form-builder-ecosystem/flutter_form_builder/issues/838
