### ISSUE TITLE
localization not working after upgrade 3.18

### ISSUE THREAD

**Issue by ddif** [flutter-form-builder-ecosystem/form_builder_validators#64]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package/Plugin version

9.1.0

### Platforms

- [X] Android
- [X] iOS
- [ ] Linux
- [ ] MacOS
- [ ] Web
- [ ] Windows

### Flutter doctor

<details>
  <summary>Flutter doctor</summary>

```bash

```

</details>

### Minimal code example

<details>
  <summary>Code sample</summary>

```dart

```

</details>

### Current Behavior

After installing Flutter version 3.18, default error messages started to appear in English whatever localization you have choosen. There was no such problem in previous versions.

### Expected Behavior

to fix that. issue

### Steps To Reproduce

in emulator and live version.

**Comment by korosiadam99** [comment]
If you use custom localization for your application, just add FormBuilderLocalizations.delegate to your delegates. 

`localizationsDelegates: const [
          FormBuilderLocalizations.delegate,
          AppLocalizations.delegate,
          GlobalMaterialLocalizations.delegate,
          GlobalWidgetsLocalizations.delegate,
          GlobalCupertinoLocalizations.delegate,
        ],`

**Comment by deandreamatias** [comment]
Please @ddif fill all sections of issue to more information and can reproduce the error. Thanks
