### ISSUE TITLE
Because form_builder_validators >=9.1.0 depends on intl ^0.18.1 

### ISSUE THREAD

**Issue by sgehrman** [flutter-form-builder-ecosystem/form_builder_validators#74]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package/Plugin version

1.1.1

### Platforms

- [ ] Android
- [ ] iOS
- [X] Linux
- [X] MacOS
- [X] Web
- [X] Windows

### Flutter doctor

<details>
  <summary>Flutter doctor</summary>

```bash
nothing
```

</details>

### Minimal code example

<details>
  <summary>Code sample</summary>

```dart
nothing
```

</details>

### Current Behavior

doesn't work

### Expected Behavior

update packs

### Steps To Reproduce

update packs

### Aditional information

sdf

**Comment by deandreamatias** [comment]
Can't update to intl 0.19 because flutter_localizations (from flutter sdk) use intl0.18.1
Take a look here https://github.com/flutter-form-builder-ecosystem/form_builder_validators/issues/73
