### ISSUE TITLE
[Features] String Validator

### ISSUE THREAD

**Issue by deandreamatias** [flutter-form-builder-ecosystem/form_builder_validators#85]
### Discussed in https://github.com/flutter-form-builder-ecosystem/form_builder_validators/discussions/84

<div type='discussions-op-text'>

<sup>Originally posted by **mstfkhazaal** April 22, 2024</sup>
Example:
`FormBuilderValidators.creditCard() return String? Function(String?)`

Add this
`FormBuilderValidators.isCeditCard(value) return bool
`
</div>

**Comment by martijn00** [comment]
Fixed in #111 

`CreditCardValidator().isCreditCard()`
