### ISSUE TITLE
Intl version 18.0.1 outdated. Does not work when using Intl 0.19.0

### ISSUE THREAD

**Issue by nietsmmar** [flutter-form-builder-ecosystem/form_builder_validators#86]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package/Plugin version

9.1.0

### Platforms

- [X] Android
- [X] iOS
- [X] Linux
- [X] MacOS
- [X] Web
- [X] Windows

### Flutter doctor

doesn't have anything to do with this issue

### Minimal code example

Trying to use this package together with `intl 0.19.0`

### Current Behavior

Can't build because flutter-form-builder depends on `intl 18.0.1`

### Expected Behavior

build without any issue

### Steps To Reproduce

add `intl: ^0.19.0` to pubspec.yaml

**Comment by deandreamatias** [comment]
Duplicated https://github.com/flutter-form-builder-ecosystem/form_builder_validators/issues/73
