### ISSUE TITLE
[General]: Incompatible with Flutter 3.22 due to dependency on intl 0.18.1

### ISSUE THREAD

**Issue by JakobLichterfeld** [flutter-form-builder-ecosystem/form_builder_validators#90]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package/Plugin version

9.0.1

### Platforms

- [X] Android
- [X] iOS
- [X] Linux
- [X] MacOS
- [X] Web
- [X] Windows

### Flutter doctor

<details>
  <summary>Flutter doctor</summary>

```bash
❯ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.22.0, on macOS 14.4.1 23E224 darwin-arm64, locale de-DE)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.3)
[✓] VS Code (version 1.89.1)
[✓] Connected device (4 available)
[✓] Network resources

• No issues found!
```

</details>

### Minimal code example

<details>
  <summary>Code sample</summary>

```yml
dependencies:
    form_builder_validators: ^9.1.0 
```

</details>

### Current Behavior

Version solving failed
```bash
flutter pub get
Resolving dependencies... 
Note: intl is pinned to version 0.19.0 by flutter_localizations from the flutter SDK.
See https://dart.dev/go/sdk-version-pinning for details.


Because every version of flutter_localizations from sdk depends on intl 0.19.0 and <package> depends on intl ^0.18.1, flutter_localizations from sdk is forbidden.
So, because <package> depends on flutter_localizations from sdk, version solving failed.
```

### Expected Behavior

Version solving possible

### Steps To Reproduce

1. Update flutter to 3.22
2. Add form_builder_validators: ^9.1.0 to `pubspec.yml`
3. run `flutter pub get`

**Comment by tylerbarnesTrexis** [comment]
Experiencing the same issue.

**Comment by JakobLichterfeld** [comment]
Workaround:
```yml
dependency_overrides:
  intl: 0.19.0   
```

**Comment by specOper99** [comment]
actually this workaround is not the best way to solve the issue cause it might has effects on some other packages which also might need to issue an update for their `pubspec.yaml`
Also, I am happy to contribute if necessary `:)`.

**Comment by JakobLichterfeld** [comment]
That's why it's called a workaround. Forking and updating the package pubspec is another one.

**Comment by jamontesg** [comment]
Experiencing the same issue.

**Comment by thicorrea1** [comment]
same issue here

**Comment by enchance** [comment]
What can we do about this?

**Comment by martijn00** [comment]
#88 will fix this

**Comment by deandreamatias** [comment]
Version 10.0.0 with fix, deployed https://pub.dev/packages/form_builder_validators
