### ISSUE TITLE
Because every version of form_builder_validators depends on flutter_localizations from sdk which depends on intl 0.19.0, every version of form_builder_validators requires intl 0.19.0.

### ISSUE THREAD

**Issue by vp-prilitya** [flutter-form-builder-ecosystem/form_builder_validators#91]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package/Plugin version

1.1.1

### Platforms

- [ ] Android
- [ ] iOS
- [ ] Linux
- [ ] MacOS
- [ ] Web
- [ ] Windows

### Flutter doctor

nothing

### Minimal code example

nothing

### Current Behavior

nothing

### Expected Behavior

nothing

### Steps To Reproduce

nothing

**Comment by JakobLichterfeld** [comment]
same as #92 which has more info and a workaround

**Comment by deandreamatias** [comment]
Version 10.0.0 with fix, deployed https://pub.dev/packages/form_builder_validators
