### ISSUE TITLE
Error reading 'form_builder_validators-10.0.0/lib/localization/intl/messages.dart': No such file or directory

### ISSUE THREAD

**Issue by jhaglund** [flutter-form-builder-ecosystem/form_builder_validators#97]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package/Plugin version

10.0.0

### Platforms

- [X] Android
- [X] iOS
- [ ] Linux
- [ ] MacOS
- [X] Web
- [ ] Windows

### Flutter doctor

<details>
  <summary>Flutter doctor</summary>

```bash

```

</details>

### Minimal code example

<details>
  <summary>Code sample</summary>

```dart

```

</details>

### Current Behavior

It appears the lib/localization/intl/ directory got deleted, at least it's broken for me. I'll see if I can restore and send a pull request but maybe [martijn00](https://github.com/flutter-form-builder-ecosystem/form_builder_validators/commits?author=martijn00) can help?

There are also a bunch of errors related to `FormBuilderLocalizationsImpl` not found/not a type.

```
lib/override_form_builder_localizations_en.dart:7:13: Error: Type 'FormBuilderLocalizationsImplEn' not found.
    extends FormBuilderLocalizationsImplEn {
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
lib/override_form_builder_localizations_en.dart:10:38: Error: Type 'FormBuilderLocalizationsImpl' not found.
  static const LocalizationsDelegate<FormBuilderLocalizationsImpl> delegate =
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
lib/override_form_builder_localizations_en.dart:21:35: Error: Type 'FormBuilderLocalizationsImpl' not found.
    extends LocalizationsDelegate<FormBuilderLocalizationsImpl> {
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
lib/override_form_builder_localizations_en.dart:25:10: Error: Type 'FormBuilderLocalizationsImpl' not found.
  Future<FormBuilderLocalizationsImpl> load(Locale locale) {
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
lib/override_form_builder_localizations_en.dart:10:38: Error: 'FormBuilderLocalizationsImpl' isn't a type.
  static const LocalizationsDelegate<FormBuilderLocalizationsImpl> delegate =
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
lib/override_form_builder_localizations_en.dart:29:30: Error: 'FormBuilderLocalizationsImpl' isn't a type.
    return SynchronousFuture<FormBuilderLocalizationsImpl>(instance);
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../lib/localization/l10n.dart:14:10: Error: Type 'FormBuilderLocalizationsImpl' not found.
  static FormBuilderLocalizationsImpl of(BuildContext context) {
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

```

### Expected Behavior

errors shouldn't appear when I upgrade

### Steps To Reproduce

upgrade to 10.0.0, build a project

**Comment by Bhavukarora03** [comment]
facing same issue with flutter form builder. just updated my sdk to 3.22.1.

**Comment by jhaglund** [comment]
Among other things, it seems `generate: true` should be set in pubspec.yaml

https://docs.flutter.dev/ui/accessibility-and-internationalization/internationalization#adding-your-own-localized-messages

**Comment by sgehrman** [comment]
same issue

**Comment by ZeroToHero-StepByStep** [comment]
A temp solution is falling back to 9.1.0 now. 

 `form_builder_validators: 9.1.0`

**Comment by jhaglund** [comment]
> A temp solution is falling back to 9.1.0 now.
> 
> `form_builder_validators: 9.1.0`

If intl 0.18.1 doesn't stop you. Or temporarily edit your pubspec.yaml to try my proposed fix

```
#  form_builder_validators: ^10.0.0
  form_builder_validators:
    git:
      url: https://github.com/jhaglund/form_builder_validators.git
      ref: main # branch name
```

**Comment by ZeroToHero-StepByStep** [comment]
Currently overriding the dependency by having `intel 0.19.0` 

  form_builder_validators: 9.1.0

# this is only temp solution as flutter_typeahead does not support 6.0.0 for now
dependency_overrides:
  flutter_colorpicker: # Keep this dependency override until flutter_colorpicker updates get published on pub.dev or until flutter_quill changes package for its color picker
    git: https://github.com/mchome/flutter_colorpicker.git
  intl: ^0.19.0 # Keep this dependency override until flutter_quill gets updated
  
  works for me. 
  
  #  form_builder_validators: ^10.0.0
  form_builder_validators:
    git:
      url: https://github.com/jhaglund/form_builder_validators.git
      ref: main # branch name
      
 Thanks for this.
